### ISSUE TITLE
Get back up

### ISSUE THREAD

**Issue by true-bilal** [mukiymike/blogging#6]
@Lemmah  @mukiymike  how bout we get this shit up and running on a .com domain

**Comment by Lemmah** [comment]
@houdinialex, @mukiymike is working on this.

**Comment by mukiymike** [comment]
@houdinialex am almost done working on a social media version of mmu shadows.It will be available next week as an app on playstore

**Comment by Lemmah** [comment]
Good stuff man! @mukiymike

**Comment by iampato** [comment]
Hey mmushadows guys.
Its the face book comment plugin still working coz mine stopped`
(https://github.com/Iampato/django-ex)

**Comment by Lemmah** [comment]
Hello @Iampato, sorry about that but we're no longer supporting this project (for some time). We are putting up plans to get back up and running soon. About the facebook plugin, I think it should still be working.
